<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Indonesian Bank Codes (3-digit)
    |--------------------------------------------------------------------------
    */
    'codes' => [
        '002' => 'Bank BRI',
        '008' => 'Bank Mandiri',
        '009' => 'Bank BNI',
        '011' => 'Bank Danamon',
        '013' => 'Bank Permata',
        '014' => 'Bank BCA',
        '016' => 'Bank Maybank',
        '019' => 'Bank Panin',
        '022' => 'Bank CIMB Niaga',
        '023' => 'Bank UOB Indonesia',
        '028' => 'Bank OCBC NISP',
        '031' => 'Bank Citibank',
        '032' => 'Bank JP Morgan Chase',
        '036' => 'Bank Artha Graha',
        '037' => 'Bank Bukopin',
        '041' => 'Bank HSBC Indonesia',
        '042' => 'Bank Mega',
        '045' => 'Bank Sumitomo Mitsui',
        '046' => 'Bank DBS Indonesia',
        '047' => 'Bank Resona Perdania',
        '048' => 'Bank Muamalat',
        '049' => 'Bank Syariah Indonesia (BSI)',
        '050' => 'Bank Jago',
        '052' => 'Bank Seabank',
        '053' => 'Bank Neo Commerce',
        '054' => 'Bank BJB',
        '055' => 'Bank BPD DIY',
        '056' => 'Bank BPD Jateng',
        '057' => 'Bank BPD Jatim',
        '058' => 'Bank BPD Bali',
        '060' => 'Bank BTN',
        '061' => 'Bank KEB Hana',
        '062' => 'Bank Shinhan',
        '063' => 'Bank Woori Saudara',
        '066' => 'Bank Commonwealth',
        '067' => 'Bank ANZ Indonesia',
        '070' => 'Bank DKI',
        '071' => 'Bank Ina Perdana',
        '072' => 'Bank Mayapada',
        '073' => 'Bank Mestika Dharma',
        '074' => 'Bank MNC Internasional',
        '076' => 'Bank SBI Indonesia',
        '077' => 'Bank Victoria',
        '088' => 'Bank BCA Syariah',
        '094' => 'Bank J Trust',
        '095' => 'Bank BNP Paribas',
        '097' => 'Bank Capital Indonesia',
        '110' => 'Bank Rakyat Indonesia (BRI)',
        '111' => 'Bank Mandiri Taspen',
        '112' => 'Bank Syariah Bukopin',
        '147' => 'Bank Index Selindo',
        '152' => 'Bank Banten',
        '153' => 'Bank BPD Kalbar',
        '154' => 'Bank BPD Kalsel',
        '155' => 'Bank BPD Kalteng',
        '156' => 'Bank BPD Kaltim',
        '157' => 'Bank BPD Sulselbar',
        '158' => 'Bank BPD Sulut',
        '159' => 'Bank BPD Sultra',
        '160' => 'Bank BPD Maluku',
        '161' => 'Bank BPD NTB',
        '162' => 'Bank BPD NTT',
        '163' => 'Bank BPD Papua',
        '164' => 'Bank BPD Riau Kepri',
        '167' => 'Bank BPD Sumut',
        '200' => 'Bank Tabungan Negara (BTN) Syariah',
        '212' => 'Bank Tabungan Pensiunan Nasional (BTPN)',
        '213' => 'Bank BTPN Syariah',
        '425' => 'Bank QNB Indonesia',
        '426' => 'Bank Ganesha',
        '441' => 'Bank China Construction Bank Indonesia',
        '459' => 'Bank CTBC Indonesia',
        '490' => 'Bank ICBC Indonesia',
        '494' => 'Bank Standard Chartered',
        '498' => 'Bank of America',
        '501' => 'Bank of China (BOC)',
        '503' => 'Bank of India Indonesia',
        '506' => 'Bank of Tokyo-Mitsubishi UFJ',
        '535' => 'Bank Sahabat Sampoerna',
        '536' => 'Bank Antar Daerah',
        '542' => 'Bank Agris',
        '547' => 'Bank Ganesha',
        '548' => 'Bank IBK Indonesia',
        '553' => 'Bank Maspion',
        '555' => 'Bank Artos',
        '558' => 'Bank Amar Indonesia',
        '559' => 'Bank Aladin Syariah',
        '562' => 'Bank Danamon Syariah',
        '564' => 'Bank Mandiri Syariah',
        '566' => 'Bank Mega Syariah',
        '567' => 'Bank Bukopin Syariah',
        '688' => 'Bank Krom',
        '790' => 'Bank Sinarmas',
        '888' => 'Bank Raya (BRI Agroniaga)',
        '945' => 'Bank Nationalnobu',
    ],
];